### ISSUE TITLE
WAN SSL Error handling

### ISSUE THREAD

**Issue by ctompkinson** [jakewmeyer/Ruby-Scripts#21]
I get the following error when running `netgeo -w`

```
☁  provision [master] ⚡ netgeo -w
/Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.2/lib/restclient/request.rb:758:in `rescue in transmit': SSL_connect returned=1 errno=0 state=error: certificate verify failed (RestClient::SSLCertificateNotVerified)
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.2/lib/restclient/request.rb:647:in `transmit'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.2/lib/restclient.rb:67:in `get'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/netgeo-0.1.0/exe/netgeo:25:in `block (2 levels) in netgeo'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/slop-4.3.0/lib/slop/option.rb:60:in `call'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/slop-4.3.0/lib/slop/option.rb:60:in `ensure_call'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/slop-4.3.0/lib/slop/parser.rb:95:in `process'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/slop-4.3.0/lib/slop/parser.rb:102:in `try_process'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/slop-4.3.0/lib/slop/parser.rb:61:in `block in parse'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/slop-4.3.0/lib/slop/parser.rb:46:in `each'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/slop-4.3.0/lib/slop/parser.rb:46:in `parse'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/slop-4.3.0/lib/slop/options.rb:71:in `parse'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/slop-4.3.0/lib/slop.rb:23:in `parse'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/netgeo-0.1.0/exe/netgeo:19:in `netgeo'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/netgeo-0.1.0/exe/netgeo:118:in `<top (required)>'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/bin/netgeo:23:in `load'
	from /Users/ctompkinson/.rbenv/versions/2.2.2/bin/netgeo:23:in `<main>'
```

I suspect this is due to missing a rescue when performing a get, which could handle and output a human readable error.

**Comment by jakewmeyer** [comment]
So there's two options here:

I'm definitely adding a handler for the error, to give a clear error message, but something weird is causing the SSL error in ```Rest-Client```. It's having issues verifying the SSL cert where you're located.

The second option  to make it go away is to add a parameter that doesn't verify the cert, but I don't know what security implications that might cause. That seems to be the consensus on that error, as described in [this issue](https://github.com/rest-client/rest-client/issues/288)

**Comment by jakewmeyer** [comment]
Another potential option is to use the non https variant of the API, that would make this a non issue as well.

**Comment by jakewmeyer** [comment]
For now, I added an exception handler to give a readable error in v0.1.2, considering options to prevent it from happening in the future.
